{% set name = "libhdbpp" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/libhdbpp/-/archive/{{ version }}/libhdbpp-{{ version }}.tar.gz
  sha256: a7465e04dfb556f910741cd95ec5126ee86dc27d7b17437130974394044c3b1a

build:
  number: 0
  skip: true  # [win]
  # Library doesn't link against cpptango (only headers used)
  ignore_run_exports:
    - cpptango
  run_exports:
    - {{ pin_subpackage('libhdbpp', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    - test -f ${PREFIX}/lib/libhdb++${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhdb++${SHLIB_EXT}.${PKG_VERSION}  # [linux]
    - test -f ${PREFIX}/lib/libhdb++.${PKG_VERSION}.dylib        # [osx]
    - test -f ${PREFIX}/include/hdb++/AbstractDB.h
    - test -f ${PREFIX}/lib/cmake/libhdbpp/libhdbppConfig.cmake

about:
  home: https://www.tango-controls.org
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Interface library for HDB++ archiving system.
  description: |
    HDB++ is an archiving system for Tango-Controls.
    libhdbpp provides an abstract means to archive data events to a Cassandra database,
    MySQL database, or potentially other database backends.
  dev_url: https://gitlab.com/tango-controls/hdbpp/libhdbpp
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/archiving/HDB++.html

extra:
  recipe-maintainers:
    - beenje
